meta-data:
  repository_name: regmonkey-shellutils
  visibility: public
  org-name: RyoNakagami
  tag:
    - shellutils
    - shellscript
    - command-line-tool
    - cli-tool
  description: |
    A collection of shell utilities for various tasks, including file management, text processing, and system monitoring. These tools are designed to enhance productivity and simplify common command-line operations.
  homepage: null
  license: mit
